
export const Consts = {
  Domain: {
    ['sandlada.com'                       ]: `https://sandlada.com`,
    ['material-design-css.sandlada.com'   ]: `https://material-design-css.sandlada.com`,
    ['mdc.sandlada.com'                   ]: `https://mdc.sandlada.com`,
    ['blog.sandlada.com'                  ]: `https://blog.sandlada.com`,
    ['kai-orion.sandlada.com'             ]: `https://kai-orion.sandlada.com`,
    ['3d-sudoku.sandlada.com'             ]: `https://3d-sudoku.sandlada.com`,
    ['material-theme-builder.sandlada.com']: `https://material-theme-builder.sandlada.com`,
    ['zhuyin-practice.sandlada.com'       ]: `https://zhuyin-practice.sandlada.com`,
  },
  Member: {
    KaiOrion: {
      Name: `kai-orion`,
      FormalName: `Kai Orion`,
      GitHubProfileLink: `https://github.com/kai-orion`,
      NpmProfileLink: `https://www.npmjs.com/~kai-orion`,
      OfficialWebLink: `https://kai-orion.sandlada.com`
    },
  },
  Repo: {
    MaterialDesignCSS: {
      Author: `Kai-Orion & Sandlada`,
      FormalName: `@sandlada/material-design-css`,
      GitHubName: `material-design-css`,
      GitHubLink: `https://github.com/sandlada/material-design-css`,
      NpmName: '@sandlada/material-design-css',
      NpmLink: `https://www.npmjs.com/package/@sandlada/material-design-css`,
      NpmDownload: `npm i @sandlada/material-design-css`,
      LicenseLink: `https://github.com/sandlada/material-design-css/blob/main/LICENSE`,
      LicenseName: `MIT`,
    },
    MDC: {
      Author: `Kai-Orion & Sandlada`,
      FormalName: `@sandlada/mdc`,
      GitHubName: `mdc`,
      GitHubLink: `https://github.com/sandlada/mdc`,
      NpmName: '@sandlada/mdc',
      NpmLink: `https://www.npmjs.com/package/@sandlada/mdc`,
      NpmDownload: `npm i @sandlada/mdc`,
      LicenseLink: `https://github.com/sandlada/mdc/blob/main/LICENSE`,
      LicenseName: `MIT`,
    },
    MDK: {
      Author: `Kai-Orion & Sandlada`,
      FormalName: `@sandlada/mdk`,
      GitHubName: `mdk`,
      GitHubLink: `https://github.com/sandlada/mdk`,
      NpmName: '@sandlada/mdk',
      NpmLink: `https://www.npmjs.com/package/@sandlada/mdk`,
      NpmDownload: `npm i @sandlada/mdk`,
      LicenseLink: `https://github.com/sandlada/mdk/blob/main/LICENSE`,
      LicenseName: `MIT`,
    },
    Result: {
      Author: `Kai-Orion & Sandlada`,
      FormalName: `@sandlada/result`,
      GitHubName: `result`,
      GitHubLink: `https://github.com/sandlada/result`,
      NpmName: '@sandlada/result',
      NpmLink: `https://www.npmjs.com/package/@sandlada/result`,
      NpmDownload: `npm i @sandlada/result`,
      LicenseLink: `https://github.com/sandlada/result/blob/main/LICENSE`,
      LicenseName: `MIT`,
    },
    Breakpoint: {
      Author: `Kai-Orion & Sandlada`,
      FormalName: `@sandlada/breakpoint`,
      GitHubName: `breakpoint`,
      GitHubLink: `https://github.com/sandlada/breakpoint`,
      NpmName: '@sandlada/breakpoint',
      NpmLink: `https://www.npmjs.com/package/@sandlada/breakpoint`,
      NpmDownload: `npm i @sandlada/breakpoint`,
      LicenseLink: `https://github.com/sandlada/breakpoint/blob/main/LICENSE`,
      LicenseName: `MIT`,
    },
    DocumentContext: {
      Author: `Kai-Orion & Sandlada`,
      FormalName: `@sandlada/document-context`,
      GitHubName: `document-context`,
      GitHubLink: `https://github.com/sandlada/document-context`,
      NpmName: '@sandlada/document-context',
      NpmLink: `https://www.npmjs.com/package/@sandlada/document-context`,
      NpmDownload: `npm i @sandlada/document-context`,
      LicenseLink: `https://github.com/sandlada/document-context/blob/main/LICENSE`,
      LicenseName: `MIT`,
    },
    VSCodeMaterialTheme: {
      Author: `Kai-Orion & Sandlada`,
      FormalName: `vscode-material-design-theme`,
      DisplayName: `Material Design 3 Theme`,
      GitHubName: `vscode-material-theme`,
      GitHubLink: `https://github.com/sandlada/vscode-material-theme`,
      Publisher: `sandlada`,
      LicenseLink: `https://github.com/sandlada/vscode-material-theme/blob/main/LICENSE`,
      LicenseName: `MIT`,
    },
    OpenCodeMaterialTheme: {
      Author: `Kai-Orion & Sandlada`,
      FormalName: `@sandlada/opencode-material-theme`,
      GitHubName: `opencode-material-theme`,
      GitHubLink: `https://github.com/sandlada/opencode-material-theme`,
      NpmName: '@sandlada/opencode-material-theme',
      NpmLink: `https://www.npmjs.com/package/@sandlada/opencode-material-theme`,
      NpmDownload: `npm i @sandlada/opencode-material-theme`,
      LicenseLink: `https://github.com/sandlada/opencode-material-theme/blob/main/LICENSE`,
      LicenseName: `MIT`,
    },
    ZedMaterialTheme: {
      Author: `Kai-Orion & Sandlada`,
      FormalName: `@sandlada/zed-material-theme`,
      DisplayName: `Material Theme`,
      GitHubName: `zed-material-theme`,
      GitHubLink: `https://github.com/sandlada/zed-material-theme`,
      NpmName: '@sandlada/zed-material-theme',
      NpmLink: `https://www.npmjs.com/package/@sandlada/zed-material-theme`,
      NpmDownload: `npm i @sandlada/zed-material-theme`,
      LicenseLink: `https://github.com/sandlada/zed-material-theme/blob/main/LICENSE`,
      LicenseName: `MIT`,
    },
    MaterialVSCodeExtensions: {
      Author: `Kai-Orion & Sandlada`,
      FormalName: `material-vscode-extensions`,
      GitHubName: `material-vscode-extensions`,
      GitHubLink: `https://github.com/sandlada/material-vscode-extensions`,
      LicenseLink: `https://github.com/sandlada/material-vscode-extensions/blob/main/LICENSE`,
      LicenseName: `MIT`,
      Extensions: {
        MaterialWebSnippets: {
          Name: `material-web-snippets`,
          DisplayName: `Material Web Snippets`,
        },
        MaterialDesignCSSSnippets: {
          Name: `material-design-css-snippets`,
          DisplayName: `Material Design CSS Snippets`,
        },
      },
    },
    MCUHelper: {
      Author: `Kai-Orion & Sandlada`,
      FormalName: `@sandlada/mcu-helper`,
      GitHubName: `mcu-helper`,
      GitHubLink: `https://github.com/sandlada/mcu-helper`,
      NpmName: '@sandlada/mcu-helper',
      NpmLink: `https://www.npmjs.com/package/@sandlada/mcu-helper`,
      NpmDownload: `npm i @sandlada/mcu-helper`,
      LicenseLink: `https://github.com/sandlada/mcu-helper/blob/main/LICENSE`,
      LicenseName: `MIT`,
    },
    MaterialThemeCLI: {
      Author: `Kai-Orion & Sandlada`,
      FormalName: `@sandlada/material-theme-cli`,
      GitHubName: `material-theme-cli`,
      GitHubLink: `https://github.com/sandlada/material-theme-cli`,
      NpmName: '@sandlada/material-theme-cli',
      NpmLink: `https://www.npmjs.com/package/@sandlada/material-theme-cli`,
      NpmDownload: `npm i @sandlada/material-theme-cli`,
      LicenseLink: `https://github.com/sandlada/material-theme-cli/blob/main/LICENSE`,
      LicenseName: `MIT`,
    },
    ComSandladaSudoku: {
      Author: `Kai-Orion & Sandlada`,
      FormalName: `com.sandlada.sudoku`,
      GitHubName: `com.sandlada.sudoku`,
      GitHubLink: `https://github.com/sandlada/com.sandlada.sudoku`,
      WebsiteLink: `https://3d-sudoku.sandlada.com`,
    },
    ComSandladaBlog: {
      Author: `Kai-Orion & Sandlada`,
      FormalName: `com.sandlada.blog`,
      GitHubName: `com.sandlada.blog`,
      GitHubLink: `https://github.com/sandlada/com.sandlada.blog`,
      WebsiteLink: `https://blog.sandlada.com`,
    },
    MaterialThemeBuilder: {
      Author: `Kai-Orion & Sandlada`,
      FormalName: `material-theme-builder`,
      GitHubName: `material-theme-builder`,
      GitHubLink: `https://github.com/sandlada/material-theme-builder`,
      WebsiteLink: `https://material-theme-builder.sandlada.com`,
      LicenseLink: `https://github.com/sandlada/material-theme-builder/blob/main/LICENSE`,
      LicenseName: `MIT`,
    },
    ComSandladaMaterialDesignCSS: {
      Author: `Kai-Orion & Sandlada`,
      FormalName: `com.sandlada.material-design-css`,
      GitHubName: `com.sandlada.material-design-css`,
      GitHubLink: `https://github.com/sandlada/com.sandlada.material-design-css`,
      WebsiteLink: `https://material-design-css.sandlada.com`,
      LicenseLink: `https://github.com/sandlada/com.sandlada.material-design-css/blob/main/LICENSE`,
      LicenseName: `MIT`,
    },
    ComSandladaZhuyinPractice: {
      Author: `Kai-Orion & Sandlada`,
      FormalName: `com.sandlada.zhuyin-practice`,
      GitHubName: `com.sandlada.zhuyin-practice`,
      GitHubLink: `https://github.com/sandlada/com.sandlada.zhuyin-practice`,
      WebsiteLink: `https://zhuyin-practice.sandlada.com`,
    },
  },
  Social: {
    Twitter: {
      Link: `https://x.com/Sandlada_team`,
    },
    GitHub: {
      Link: `https://github.com/sandlada`,
    },
    Npm: {
      Link: `https://www.npmjs.com/org/sandlada`,
    },
  }
} as const
